import { Prisma } from "@prisma/client";
import { db } from "@/lib/db";
import { getCart } from "@/lib/services/cart";

const orderInclude = { items: { include: { product: true, variant: true } } };
export const orderDto = (order: any) => ({ ...order, subtotal: Number(order.subtotal), discount: Number(order.discount), shipping: Number(order.shipping), total: Number(order.total), items: order.items.map((item: any) => ({ ...item, unitPrice: Number(item.unitPrice) })) });
export function shippingEstimate(postalCode: string, country: string, subtotal = 0) { const domestic = country.toUpperCase() === "US"; const remote = /^(99|00)/.test(postalCode); const shippingCost = subtotal >= 500 ? 0 : domestic ? remote ? 18 : 12 : 28; return { available: true, estimatedDays: domestic ? remote ? 5 : 3 : 8, shippingCost }; }
export async function checkout(userId: string, addressId: string) {
  const address = await db.address.findFirst({ where: { id: addressId, userId } }); if (!address) throw new Error("ADDRESS_NOT_FOUND");
  const cart = await getCart(userId); if (!cart.items.length) throw new Error("CART_EMPTY");
  const result = await db.$transaction(async (tx) => { const hydrated = await tx.cart.findUniqueOrThrow({ where: { userId }, include: { coupon: true, items: { include: { product: true, variant: true } } } }); let subtotal = new Prisma.Decimal(0); for (const item of hydrated.items) { const available = item.variant?.stock ?? item.product.stock; if (available < item.quantity) throw new Error("INSUFFICIENT_STOCK"); subtotal = subtotal.plus((item.variant?.price ?? item.product.price).mul(item.quantity)); }
    let discount = new Prisma.Decimal(0); if (hydrated.coupon) { if (hydrated.coupon.type === "PERCENTAGE") discount = subtotal.mul(hydrated.coupon.value).div(100); else if (hydrated.coupon.type === "FIXED") discount = hydrated.coupon.value; if (discount.gt(subtotal)) discount = subtotal; }
    const estimate = shippingEstimate(address.postalCode, address.country, subtotal.toNumber()); const shipping = hydrated.coupon?.type === "SHIPPING" ? new Prisma.Decimal(0) : new Prisma.Decimal(estimate.shippingCost); const order = await tx.order.create({ data: { userId, addressSnapshot: address, status: "PAID", subtotal, discount, shipping, total: subtotal.minus(discount).plus(shipping), couponCode: hydrated.coupon?.code, items: { create: hydrated.items.map((item) => ({ productId: item.productId, variantId: item.variantId, name: item.product.name, sku: item.variant?.sku, unitPrice: item.variant?.price ?? item.product.price, quantity: item.quantity })) } }, include: orderInclude });
    for (const item of hydrated.items) { if (item.variantId) await tx.productVariant.update({ where: { id: item.variantId }, data: { stock: { decrement: item.quantity } } }); else await tx.product.update({ where: { id: item.productId }, data: { stock: { decrement: item.quantity } } }); }
    if (hydrated.coupon) await tx.coupon.update({ where: { id: hydrated.coupon.id }, data: { usedCount: { increment: 1 } } }); await tx.cartItem.deleteMany({ where: { cartId: hydrated.id } }); await tx.cart.update({ where: { id: hydrated.id }, data: { couponId: null } }); return orderDto(order); }); return result;
}
export async function getOrders(userId: string) { return (await db.order.findMany({ where: { userId }, include: orderInclude, orderBy: { createdAt: "desc" } })).map(orderDto); }
export async function getOrder(userId: string, id: string) { const order = await db.order.findFirst({ where: { id, userId }, include: orderInclude }); return order ? orderDto(order) : null; }
export async function cancelOrder(userId: string, id: string) { const order = await db.order.findFirst({ where: { id, userId }, include: orderInclude }); if (!order) throw new Error("ORDER_NOT_FOUND"); if (!["PENDING", "PAID", "PROCESSING"].includes(order.status)) throw new Error("ORDER_NOT_CANCELLABLE"); return orderDto(await db.$transaction(async (tx) => { for (const item of order.items) { if (item.variantId) await tx.productVariant.update({ where: { id: item.variantId }, data: { stock: { increment: item.quantity } } }); else await tx.product.update({ where: { id: item.productId }, data: { stock: { increment: item.quantity } } }); } return tx.order.update({ where: { id }, data: { status: "CANCELLED" }, include: orderInclude }); })); }
