import Link from "next/link";
import { db } from "@/lib/db";
import { searchProducts } from "@/lib/services/products";
export const dynamic = "force-dynamic";

export default async function HomePage() {
  const [categories, featured, popular] = await Promise.all([db.category.findMany({ orderBy: { name: "asc" } }), searchProducts({ page: 1, limit: 4, sort: "newest" }), searchProducts({ page: 1, limit: 4, sort: "popularity" })]);
  const Grid = ({ products }: { products: typeof featured.products }) => <div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{products.map((product) => <Link key={product.id} href={`/products/${product.slug}`} className="rounded-lg border bg-white p-5 shadow-sm"><div className="mb-4 aspect-[4/3] rounded bg-slate-100" /><p className="text-sm text-slate-500">{product.brand}</p><h3 className="mt-1 font-semibold">{product.name}</h3><p className="mt-3 font-semibold">${product.price.toFixed(2)}</p></Link>)}</div>;
  return <main><section className="mx-auto max-w-6xl px-6 py-24"><p className="mb-3 text-sm font-semibold tracking-widest text-sky-700">RELIABLE TECHNOLOGY</p><h1 className="max-w-3xl text-5xl font-bold tracking-tight">Technology selected for everyday work.</h1><p className="mt-6 max-w-xl text-lg text-slate-600">AgentBridge brings together considered hardware and practical accessories from trusted brands.</p><Link href="/products" className="mt-8 inline-block rounded-md bg-slate-900 px-5 py-3 text-sm font-semibold text-white">Shop products</Link></section><section className="border-y bg-white"><div className="mx-auto max-w-6xl px-6 py-14"><div className="flex items-end justify-between"><h2 className="text-2xl font-bold">Shop by category</h2><Link className="text-sm underline" href="/products">View all</Link></div><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-7">{categories.map((category) => <Link key={category.id} href={`/search?q=${encodeURIComponent(category.name)}`} className="rounded border bg-slate-50 p-4 text-center text-sm font-medium">{category.name}</Link>)}</div></div></section><section className="mx-auto max-w-6xl px-6 py-14"><h2 className="text-2xl font-bold">Featured products</h2><Grid products={featured.products} /></section><section className="bg-slate-900"><div className="mx-auto max-w-6xl px-6 py-14 text-white"><p className="text-sm font-semibold tracking-widest text-sky-300">THE AGENTBRIDGE STANDARD</p><h2 className="mt-3 max-w-xl text-3xl font-bold">Dependable gear, clear choices, and no unnecessary noise.</h2></div></section><section className="mx-auto max-w-6xl px-6 py-14"><h2 className="text-2xl font-bold">Popular now</h2><Grid products={popular.products} /></section></main>;
}
